# Generated by Django 2.0.7 on 2018-09-03 02:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia-threaded-comments', '0002_migrate_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadedcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='zinnia-threaded-comments.ThreadedComment', verbose_name='reply in comment'),
        ),
    ]
